title: QTVPlayer
description: кросс-платформенный IPTV медиаплеер
show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/programstroy/QTVPlayer-release/tree/master/playlist/ChannelsList.user.xml
